export const FEATURED_EVENTS_REQUEST = 'FEATURED_EVENTS_REQUEST';
export const FEATURED_EVENTS_SUCCESS = 'FEATURED_EVENTS_SUCCESS';
export const FEATURED_EVENTS_FAILED = 'FEATURED_EVENTS_FAILED';
export const SEARCH_EVENTS_REQUEST = 'SEARCH_EVENTS_REQUEST';
export const SEARCH_EVENTS_SUCCESS = 'SEARCH_EVENTS_SUCCESS';
export const SEARCH_EVENTS_FAILED = 'SEARCH_EVENTS_FAILED';
